services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm run dev
