services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=DEV
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm run dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=DEV
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
